TRAIN:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 6
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: False
  TPU_ENABLE: False
OUTPUT_DIR: ./checkpoints/moose_biconcat_sapiens_8frame_1024_maskarrow_timemean/
MODEL:
  MODEL_NAME: MOOSE
  NUM_CLASSES: 400
  ARCH: vit
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
  FUSION_MODE: biconcat
  VISUAL_MODEL: sapiens
  TIME_AGGREGATION: mean
  ST_MASKING: arrow
DATA:
  PATH_TO_DATA_DIR: /data1/hongn/kinetics-dataset/k400
  NUM_FRAMES: 2
  SAMPLING_RATE: 8
  TRAIN_JITTER_SCALES: [1024, 1152]
  TRAIN_CROP_SIZE: 1024
  TEST_CROP_SIZE: 1024
  INPUT_CHANNEL_NUM: [3]
  PATH_LABEL_SEPARATOR: ","
TIMESFORMER:
  ATTENTION_TYPE: 'divided_space_time'
SOLVER:
  BASE_LR: 0.005
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 11, 14]
  LRS: [1, 0.1, 0.01]
  MAX_EPOCH: 21
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  OPTIMIZING_METHOD: sgd
TEST:
  ENABLE: False
  DATASET: kinetics
  BATCH_SIZE: 1
  NUM_ENSEMBLE_VIEWS: 1
  NUM_SPATIAL_CROPS: 3
DATA_LOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: True
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
